version: "2.1"
services:    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - esdata2:/usr/share/elasticsearch/logs
    ports:
      - ${PORT_ES}:9200
      - 9300:9300
    healthcheck:
      test: "exit 0"

volumes:
  esdata1:
    driver: local
  esdata2: 
    driver: local

